name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: denoland/setup-deno@v1
      with:
        deno-version: v1.x

    - run: deno fmt --check

    # ui-vue/
    - run: cd ui-vue && npm install
    # patch node_modules/@mdi/font/css/
    - run: cd ui-vue/node_modules/@mdi/font/css && patch -p2 < ../../../../../uis/patch/1.patch
    - run: deno run -A uis/patch/fix_font_name.js ui-vue/node_modules/@mdi/font/css/materialdesignicons.css pmim-ui

    - run: cd ui-vue && npm run build

    # build lo
    - run: cd ui-vue/dist && ln -s assets/lo1-*.js lo1.js
    - run: cd ui-vue && npx webpack
    - run: rm ui-vue/dist/lo1.js
    - run: cd ui-vue && deno run --allow-read lo/fix.js dist/lo1/index.html > dist/lo/index.html

    - run: |
        tar --zstd -cvf ui-vue-dist.tar.zst \
        ui-vue/dist
    - uses: actions/upload-artifact@v4
      with:
        name: ui-vue-dist
        path: ui-vue-dist.tar.zst

    # uis/pmim-uis-nc
    - run: cd uis/pmim-uis-nc && npm install
    # patch node_modules/@mdi/font/css/
    - run: cd uis/pmim-uis-nc/node_modules/@mdi/font/css && patch -p2 < ../../../../../patch/2.patch
    - run: deno run -A uis/patch/fix_font_name.js uis/pmim-uis-nc/node_modules/@mdi/font/css/materialdesignicons.css pmim-uis-nc

    - run: cd uis/pmim-uis-nc && npm run build
    - run: cp uis/pmim-uis-nc/node_modules/@mdi/font/fonts/materialdesignicons-webfont.woff2 uis/pmim-uis-nc/dist
    - run: deno run -A uis/patch/fix_css_font.js uis/pmim-uis-nc/dist/style.css

    # TODO
    # uis/pmim-uis-bl
    #- run: cd uis/pmim-uis-bl && npm install
    # patch node_modules/@mdi/font/css/
    #- run: cd uis/pmim-uis-bl/node_modules/@mdi/font/css && patch -p2 < ../../../../../patch/2.patch
    #- run: deno run -A uis/patch/fix_font_name.js uis/pmim-uis-bl/node_modules/@mdi/font/css/materialdesignicons.css pmim-uis-bl

    #- run: cd uis/pmim-uis-bl && npm run build
    #- run: cp uis/pmim-uis-bl/node_modules/@mdi/font/fonts/materialdesignicons-webfont.woff2 uis/pmim-uis-bl/dist
    #- run: deno run -A uis/patch/fix_css_font.js uis/pmim-uis-bl/dist/style.css

    # plugin
    - run: mkdir -p plugin/pmim-uis-nc/static && cp -r uis/pmim-uis-nc/dist/* plugin/pmim-uis-nc/static
    #- run: mkdir -p plugin/pmim-uis-bl/static && cp -r uis/pmim-uis-bl/dist/* plugin/pmim-uis-bl/static

    - run: |
        tar --zstd -cvf pmim-plugin.tar.zst \
        plugin
    - uses: actions/upload-artifact@v4
      with:
        name: pmim-plugin
        path: pmim-plugin.tar.zst

  flatpak:
    needs: build
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-45
      options: --privileged
    steps:
    - uses: actions/checkout@v4

    - run: dnf -y install npm

    # build (ui-vue/dist)
    - run: cd ui-vue && npm install
    - run: cd ui-vue && npm run build

    - run: mkdir -p flatpak/build_src

    # deno
    - uses: robinraju/release-downloader@v1
      with:
        repository: "denoland/deno"
        tag: "v1.41.2"
        fileName: "deno-x86_64-unknown-linux-gnu.zip"
    - run: mv deno-x86_64-unknown-linux-gnu.zip flatpak/build_src

    # electronjs dist
    - uses: robinraju/release-downloader@v1
      with:
        repository: "electron/electron"
        tag: "v29.1.4"
        fileName: "electron-v29.1.4-linux-x64.zip"
    - run: mv electron-v29.1.4-linux-x64.zip flatpak/build_src/electron.zip

    # ibrus
    - uses: robinraju/release-downloader@v1
      with:
        repository: "fm-elpac/librush"
        tag: "v0.1.0-a2"
        fileName: "librush_release_x86_64-unknown-linux-gnu.tar.zst"
    - run: mv librush_release_x86_64-unknown-linux-gnu.tar.zst flatpak/build_src

    # pmim-server
    - uses: robinraju/release-downloader@v1
      with:
        repository: "fm-elpac/pmim"
        tag: "v0.1.3"
        fileName: "pmim-server.tar.zst"
    - run: mv pmim-server.tar.zst flatpak/build_src

    # pmim-data
    - uses: robinraju/release-downloader@v1
      with:
        repository: "fm-elpac/pmim-data"
        tag: "v0.1.1"
        fileName: "pmim_sys-0.db.zst"
    - run: mv pmim_sys-0.db.zst flatpak/build_src

    - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
      with:
        bundle: pmim_ibus.flatpak
        manifest-path: flatpak/io.github.fm_elpac.pmim_ibus.yml

  # TODO
